/**
 * GET /api/session/learn-more?sessionId=xxx
 *
 * Returns rich help content for the current concept in a session.
 * Content is generated by Claude and cached in Redis for 24 hours.
 * Used by the LearnPanel component during practice phases.
 */

import { NextResponse } from "next/server";
import { prisma } from "@aauti/db";
import { callClaude } from "@/lib/session/claude-client";
import {
  buildLearnMorePrompt,
  parseLearnMoreResponse,
} from "@/lib/prompts/learn-more.prompt";
import { getRedisClient, buildCacheKey } from "@/lib/cache/redis-client";
import type { AgeGroupValue, LearnMoreContent } from "@/lib/prompts/types";

export const maxDuration = 30;

const CACHE_TTL = 24 * 60 * 60; // 24 hours

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const sessionId = searchParams.get("sessionId");

  if (!sessionId) {
    return NextResponse.json(
      { error: "sessionId is required" },
      { status: 400 }
    );
  }

  // Fetch session with node + student info
  const session = await prisma.learningSession.findUnique({
    where: { id: sessionId },
    include: { student: true, currentNode: true },
  });

  if (!session?.currentNode || !session.student) {
    return NextResponse.json(
      { error: "Session not found" },
      { status: 404 }
    );
  }

  const node = session.currentNode;
  const student = session.student;
  const ageGroup = student.ageGroup as AgeGroupValue;

  // Check Redis cache
  const cacheKeyStr = buildCacheKey(
    "learn-more",
    node.id,
    ageGroup,
    student.avatarPersonaId
  );

  try {
    const redis = await getRedisClient();
    if (redis) {
      const cached = await redis.get(cacheKeyStr);
      if (cached) {
        console.log(
          `[learn-more] Cache HIT for ${node.title} (${cacheKeyStr})`
        );
        const content = JSON.parse(cached) as LearnMoreContent;
        return NextResponse.json({ content, source: "cache" });
      }
    }
  } catch (e) {
    console.warn("[learn-more] Redis cache check error (non-critical):", e);
  }

  // Generate via Claude
  console.log(
    `[learn-more] Cache MISS — generating for "${node.title}" (${node.nodeCode})`
  );

  const promptParams = {
    nodeTitle: node.title,
    nodeDescription: node.description,
    gradeLevel: node.gradeLevel,
    domain: node.domain,
    difficulty: node.difficulty,
    ageGroup,
    personaId: student.avatarPersonaId,
  };

  const prompt = buildLearnMorePrompt(promptParams);
  const claudeResponse = await callClaude(prompt, { maxTokens: 2048 });

  if (claudeResponse) {
    const content = parseLearnMoreResponse(claudeResponse);
    if (content) {
      // Cache in Redis
      try {
        const redis = await getRedisClient();
        if (redis) {
          await redis.set(cacheKeyStr, JSON.stringify(content), {
            EX: CACHE_TTL,
          });
          console.log(`[learn-more] Cached content for ${node.title}`);
        }
      } catch (e) {
        console.warn("[learn-more] Redis cache store error:", e);
      }

      return NextResponse.json({ content, source: "generated" });
    }
    console.warn(`[learn-more] Parse failed for ${node.title}`);
  }

  // Fallback content
  console.warn(`[learn-more] Using fallback content for ${node.title}`);
  const fallback = generateFallbackContent(
    node.title,
    node.description,
    node.domain
  );
  return NextResponse.json({ content: fallback, source: "fallback" });
}

function generateFallbackContent(
  title: string,
  description: string,
  domain: string
): LearnMoreContent {
  const isMath =
    !["GRAMMAR", "READING", "WRITING", "VOCABULARY"].includes(domain);

  return {
    definition: `${title} is an important concept that helps you ${isMath ? "solve math problems" : "understand language better"}!`,
    steps: [
      {
        label: "Step 1: Understand the idea",
        visual: isMath ? "🔢 Numbers" : "📖 Words",
        narration: `Let's start by understanding what ${title} means. ${description}`,
      },
      {
        label: "Step 2: See an example",
        visual: isMath ? "✏️ Practice" : "✍️ Practice",
        narration: `Now let's look at a simple example. This will help you see how ${title} works in action.`,
      },
      {
        label: "Step 3: Try it yourself",
        visual: "💪 Your turn!",
        narration:
          "Now it's your turn! Go back to the practice question and give it your best shot. You've got this!",
      },
    ],
    examples: [
      {
        problem: `Practice problem for ${title}`,
        steps: [
          "Read the problem carefully",
          "Think about what you learned",
          "Try to solve it step by step",
        ],
        answer: "Try solving this in the practice section!",
        tip: "Take your time and think through each step.",
      },
    ],
    faqs: [
      {
        question: `What is ${title}?`,
        answer: description,
      },
      {
        question: "Why do I need to learn this?",
        answer: `${title} is a building block for more advanced concepts. Mastering it now will make future topics much easier!`,
      },
      {
        question: "What if I get it wrong?",
        answer:
          "That's totally okay! Making mistakes is how we learn. Each wrong answer helps you understand the concept better.",
      },
    ],
  };
}
