"use client";

/**
 * Child Reports Page — Phase 9: Parent Dashboard
 *
 * Weekly narrative reports generated by Claude.
 * Shows latest report + list of previous reports.
 */

import { useState, useEffect, useCallback } from "react";
import { useParams } from "next/navigation";

interface ReportSummary {
  id: string;
  weekStart: string;
  weekEnd: string;
  reportText: string;
  stats: {
    totalSessions: number;
    totalTimeMinutes: number;
    questionsAnswered: number;
    overallAccuracy: number;
    nodesMastered: number;
    streakDays: number;
    badgesEarned: number;
    emotionalScore: number;
  };
  generatedAt: string;
  viewedAt: string | null;
}

export default function ChildReportsPage() {
  const params = useParams();
  const childId = params.id as string;

  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [latestReport, setLatestReport] = useState<ReportSummary | null>(null);
  const [previousReports, setPreviousReports] = useState<ReportSummary[]>([]);
  const [selectedReport, setSelectedReport] = useState<ReportSummary | null>(
    null
  );

  const fetchReports = useCallback(async () => {
    try {
      const res = await fetch(`/api/parent/child/${childId}/reports`);
      if (res.ok) {
        const data = await res.json();
        setLatestReport(data.latest || null);
        setPreviousReports(data.previous || []);
        if (data.latest) setSelectedReport(data.latest);
      }
    } catch (err) {
      console.error("Failed to load reports:", err);
    } finally {
      setLoading(false);
    }
  }, [childId]);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const res = await fetch(`/api/parent/child/${childId}/reports/generate`, {
        method: "POST",
      });
      if (res.ok) {
        await fetchReports();
      }
    } catch (err) {
      console.error("Failed to generate report:", err);
    } finally {
      setGenerating(false);
    }
  };

  if (loading) {
    return (
      <div className="animate-pulse text-gray-400 py-12 text-center">
        Loading reports...
      </div>
    );
  }

  const displayReport = selectedReport || latestReport;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-gray-900">Weekly Reports</h2>
          <p className="text-sm text-gray-500 mt-1">
            AI-generated summaries of your child&apos;s learning journey.
          </p>
        </div>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="px-4 py-2 bg-purple-600 hover:bg-purple-500 disabled:opacity-50 text-white rounded-lg text-sm font-medium transition-colors"
        >
          {generating ? "Generating..." : "Generate This Week's Report"}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Report Content */}
        <div className="lg:col-span-2">
          {displayReport ? (
            <div className="bg-white rounded-xl border border-gray-100 p-6">
              {/* Report Header */}
              <div className="flex items-center justify-between mb-4 pb-4 border-b border-gray-100">
                <div>
                  <h3 className="font-semibold text-gray-900">
                    Week of{" "}
                    {new Date(displayReport.weekStart).toLocaleDateString(
                      "en-US",
                      { month: "long", day: "numeric" }
                    )}{" "}
                    –{" "}
                    {new Date(displayReport.weekEnd).toLocaleDateString(
                      "en-US",
                      {
                        month: "long",
                        day: "numeric",
                        year: "numeric",
                      }
                    )}
                  </h3>
                  <p className="text-xs text-gray-400 mt-1">
                    Generated{" "}
                    {new Date(displayReport.generatedAt).toLocaleDateString()}
                  </p>
                </div>
              </div>

              {/* Report Prose */}
              <div className="prose prose-sm max-w-none text-gray-700 leading-relaxed whitespace-pre-line">
                {displayReport.reportText}
              </div>

              {/* Stats Summary */}
              <div className="mt-6 pt-4 border-t border-gray-100 grid grid-cols-2 md:grid-cols-4 gap-4">
                <StatBox
                  label="Sessions"
                  value={String(displayReport.stats.totalSessions)}
                />
                <StatBox
                  label="Time"
                  value={`${displayReport.stats.totalTimeMinutes}m`}
                />
                <StatBox
                  label="Accuracy"
                  value={`${Math.round(displayReport.stats.overallAccuracy * 100)}%`}
                />
                <StatBox
                  label="Mastered"
                  value={String(displayReport.stats.nodesMastered)}
                />
              </div>
            </div>
          ) : (
            <div className="bg-white rounded-xl border border-gray-100 p-8 text-center">
              <div className="text-4xl mb-3">📝</div>
              <h3 className="font-semibold text-gray-900 mb-1">
                No Reports Yet
              </h3>
              <p className="text-sm text-gray-500 mb-4">
                Click &quot;Generate This Week&apos;s Report&quot; to create
                your first weekly summary.
              </p>
            </div>
          )}
        </div>

        {/* Report List */}
        <div className="bg-white rounded-xl border border-gray-100 p-4">
          <h4 className="font-semibold text-gray-900 text-sm mb-3">
            Previous Reports
          </h4>
          {previousReports.length > 0 ? (
            <div className="space-y-2">
              {previousReports.map((report) => (
                <button
                  key={report.id}
                  onClick={() => setSelectedReport(report)}
                  className={`w-full text-left px-3 py-2 rounded-lg text-sm transition-colors ${
                    selectedReport?.id === report.id
                      ? "bg-purple-50 text-purple-700"
                      : "text-gray-600 hover:bg-gray-50"
                  }`}
                >
                  <p className="font-medium">
                    {new Date(report.weekStart).toLocaleDateString("en-US", {
                      month: "short",
                      day: "numeric",
                    })}{" "}
                    –{" "}
                    {new Date(report.weekEnd).toLocaleDateString("en-US", {
                      month: "short",
                      day: "numeric",
                    })}
                  </p>
                  <p className="text-xs text-gray-400 mt-0.5">
                    {report.stats.totalSessions} sessions ·{" "}
                    {Math.round(report.stats.overallAccuracy * 100)}% accuracy
                  </p>
                </button>
              ))}
            </div>
          ) : (
            <p className="text-sm text-gray-400 text-center py-4">
              Reports will appear here after generation.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

function StatBox({ label, value }: { label: string; value: string }) {
  return (
    <div className="text-center">
      <p className="text-lg font-bold text-purple-600">{value}</p>
      <p className="text-xs text-gray-400">{label}</p>
    </div>
  );
}
