/**
 * Terms of Service — required for App Store submission.
 */

export const metadata = {
  title: "Terms of Service — Aauti Learn",
  description: "Terms of Service for the Aauti Learn educational platform.",
};

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-white py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold text-gray-900 mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-gray-500 mb-10">
          Last updated: March 11, 2026
        </p>

        <div className="prose prose-gray max-w-none">
          <Section title="1. Acceptance of Terms">
            <p>
              By accessing or using Aauti Learn (&quot;the Service&quot;), you
              agree to be bound by these Terms of Service. If you are a parent
              or guardian creating an account for a child, you agree to these
              terms on behalf of your child.
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              Aauti Learn is an AI-powered adaptive tutoring platform that
              provides personalized K-12 educational content in mathematics and
              English language arts. The Service includes a web application and
              mobile application.
            </p>
          </Section>

          <Section title="3. Account Registration">
            <ul className="list-disc pl-6 space-y-1">
              <li>
                Parent accounts require a valid email address and are managed
                through our authentication system.
              </li>
              <li>
                Child accounts are created by parents and accessed using a
                username and PIN set by the parent.
              </li>
              <li>
                You are responsible for maintaining the security of your
                account credentials.
              </li>
              <li>
                You must be at least 18 years old to create a parent account.
              </li>
            </ul>
          </Section>

          <Section title="4. Acceptable Use">
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                Use the Service for any unlawful purpose or in violation of
                these Terms
              </li>
              <li>
                Attempt to gain unauthorized access to the Service or its
                systems
              </li>
              <li>
                Interfere with or disrupt the Service or its infrastructure
              </li>
              <li>
                Share account credentials with unauthorized individuals
              </li>
              <li>
                Use the Service to collect information about other users
              </li>
              <li>
                Reverse engineer, decompile, or disassemble any part of the
                Service
              </li>
            </ul>
          </Section>

          <Section title="5. Intellectual Property">
            <p>
              All content, features, and functionality of the Service,
              including but not limited to educational content, software, text,
              graphics, logos, and icons, are owned by Aauti Learn and are
              protected by copyright, trademark, and other intellectual property
              laws.
            </p>
            <p>
              Learning progress data generated by students belongs to the
              student and their parent/guardian. Parents may request export or
              deletion of this data at any time.
            </p>
          </Section>

          <Section title="6. AI-Generated Content">
            <p>
              The Service uses artificial intelligence to generate educational
              content, including questions, explanations, and teaching
              materials. While we strive for accuracy, AI-generated content
              may occasionally contain errors. The Service is intended to
              supplement, not replace, formal education.
            </p>
          </Section>

          <Section title="7. Subscription and Payments">
            <p>
              Certain features of the Service may require a paid subscription.
              Payment terms, pricing, and refund policies are provided at the
              time of purchase. Free tier features are available without
              payment.
            </p>
          </Section>

          <Section title="8. Disclaimer of Warranties">
            <p>
              The Service is provided &quot;as is&quot; and &quot;as
              available&quot; without warranties of any kind, either express or
              implied. We do not warrant that the Service will be
              uninterrupted, error-free, or free of harmful components.
            </p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>
              To the maximum extent permitted by law, Aauti Learn shall not be
              liable for any indirect, incidental, special, consequential, or
              punitive damages arising out of or related to your use of the
              Service.
            </p>
          </Section>

          <Section title="10. Termination">
            <p>
              We may suspend or terminate your access to the Service at any
              time for violation of these Terms. You may terminate your account
              at any time by contacting us. Upon termination, your right to use
              the Service will immediately cease.
            </p>
          </Section>

          <Section title="11. Changes to Terms">
            <p>
              We reserve the right to modify these Terms at any time. We will
              notify users of material changes via email or in-app notification.
              Continued use of the Service after changes constitutes acceptance
              of the modified Terms.
            </p>
          </Section>

          <Section title="12. Governing Law">
            <p>
              These Terms shall be governed by and construed in accordance with
              the laws of the United States, without regard to conflict of law
              principles.
            </p>
          </Section>

          <Section title="13. Contact">
            <p>
              For questions about these Terms, please contact us:
            </p>
            <p className="mt-2">
              <strong>Email:</strong>{" "}
              <a
                href="mailto:support@aautilearn.com"
                className="text-purple-600 hover:underline"
              >
                support@aautilearn.com
              </a>
            </p>
          </Section>
        </div>
      </div>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-4">{title}</h2>
      <div className="text-gray-700 leading-relaxed space-y-3">
        {children}
      </div>
    </section>
  );
}
